### PR TITLE
first script idea

### LINKED ISSUE #63: Prepare dev environment
As a contributor I want to contribute fast. I don't want to do a bunch of steps until i can do the "real" work. 
So a script which support or guide the contributor to setup the dev environment as much as possible.

### PR DESCRIPTION
**Pull request by Cinux90**
resolve: #63 

currently todo:

- [x] improve output
- [x] expect a empty input 
- [x] expect unexpected input
- [x] some details how to start now (activate env, trigger tests etc.)
- [x] expect everytime keyboard interrupt
- [x] cleanup after work
- [x] help page - not needed its guided
- [x] check if docker is running

@while-true-do/ansible-developer: Feel free to bring ideas

### CODE REVIEW

**Comment by Cinux90** [comment]
ok. For me the script looks ok.
Its a bit quick and dirty and not perfect but it helps with the first steps.

Feel free to review :)

**Comment by Cinux90** [comment]
@daniel-wtd feel free to review :)

**Review by dschier-wtd — CHANGES_REQUESTED** [review]
@Cinux90 I had a review and it looks quite ok. I recommend the following steps:

- remove the "create role stuff" -> currently it's only 2 steps
- check with a linter like flake8
- the ansible cfg seems to be written relative to the execution path, someone can have other stuff in there or multiple configurations and we should avoid directly manipulate such stuff. it's better to output the needed steps at the end.
- a little bit more documentation in the code would be awesome at least each `def` should be documented to use some auto-doc tools in a later process
Otherwise, cool work

**Comment by Cinux90** [comment]
ty for review. If the weather will be colder i will have a look.. ;)

**Comment by dschier-wtd** [comment]
stale for ages -> remove

**Pull request closed without merging**
